# Generated by Django 3.2.5 on 2023-04-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20230418_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='add_to_index',
            field=models.BooleanField(default=False, verbose_name='添加到首页'),
        ),
    ]
