# Generated by Django 3.2.5 on 2023-04-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_tag_add_to_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='文章描述'),
        ),
    ]
