# Generated by Django 3.2.5 on 2023-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index_banner',
            field=models.URLField(default='http://42.193.14.111/static/upload/tsxywts/banner1.jpg', verbose_name='主页品牌封面'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.URLField(default='http://42.193.14.111/static/upload/tsxywts/banner6.jpg', verbose_name='详情页品牌封面'),
        ),
    ]
