# Generated by Django 3.2.5 on 2023-05-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendshiplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='友链名称')),
                ('introduction_url', models.URLField(default='http://tsxy.zuel.edu.cn/', max_length=250, verbose_name='友链链接')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
        migrations.CreateModel(
            name='Teammember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名（昵称）')),
                ('desc', models.CharField(max_length=100, verbose_name='人物简介')),
                ('photo', models.URLField(default='http://42.193.14.111/static/upload/tsxywts/testi2.jpg', verbose_name='照片链接')),
                ('introduction_url', models.URLField(default='https://mp.weixin.qq.com/s/gkeOZMPFoQQdMH5kM_sYCQ', max_length=250, verbose_name='人物介绍链接')),
                ('button_word', models.CharField(default='点击了解', max_length=10, verbose_name='跳转文字')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='视频名称')),
                ('video_url', models.URLField(default='http://tsxy.zuel.edu.cn/', max_length=250, verbose_name='视频链接')),
            ],
            options={
                'verbose_name': '首页宣传视频',
                'verbose_name_plural': '首页宣传视频',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterField(
            model_name='department',
            name='avatar',
            field=models.URLField(default='http://42.193.14.111/static/upload/tsxywts/testi2.jpg', verbose_name='部门头像'),
        ),
    ]
