# Generated by Django 3.2.5 on 2023-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_auto_20230517_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshiplink',
            options={'ordering': ('sort_num',), 'verbose_name': '友链', 'verbose_name_plural': '友链'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('sort_num',), 'verbose_name': '人物', 'verbose_name_plural': '人物'},
        ),
        migrations.AddField(
            model_name='friendshiplink',
            name='sort_num',
            field=models.IntegerField(default=1, verbose_name='展示顺序'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='sort_num',
            field=models.IntegerField(default=1, verbose_name='展示顺序'),
        ),
    ]
